dependencies {
    api libs.reactor.core
    api libs.servicer
    api libs.jackson.databind
    annotationProcessor libs.servicer

    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter.engine
    testAnnotationProcessor libs.servicer
    testRuntimeOnly libs.junit.platform.launcher
}

jar {
    manifest {
        attributes 'Implementation-Title': base.archivesName.get(),
                'Implementation-Version': archiveVersion,
                'Automatic-Module-Name': 'discord4j.store.api'
    }
}
